apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-lifecycle-controller
  namespace: lifecycle-system
  labels:
    app.kubernetes.io/name: workload-lifecycle-controller
    app.kubernetes.io/part-of: workload-lifecycle-controller
automountServiceAccountToken: true
